#-----------------------------------------------------------
# Global or/and default variables
#-----------------------------------------------------------
variable "name" {
  description = "Name to be used on all resources as prefix"
  default     = "TEST"
}

variable "environment" {
  description = "Environment for service"
  default     = "STAGE"
}

variable "tags" {
  description = "Add additional tags"
  default     = {}
}

#---------------------------------------------------
# AWS cloudfront distribution
#---------------------------------------------------
variable "enable_cloudfront_distribution" {
  description = "Enable cloudfront distribution usage"
  default     = false
}

variable "cloudfront_distribution_stack" {
  description = "Set properties for cloudfront distribution"
  default     = []
}

#---------------------------------------------------
# AWS cloudfront public key
#---------------------------------------------------
variable "enable_cloudfront_public_key" {
  description = "Enable cloudfront public key usage"
  default     = false
}

variable "cloudfront_public_key_encoded_key" {
  description = "(Required) The encoded public key that you want to add to CloudFront to use with features like field-level encryption."
  default     = ""
}

variable "cloudfront_public_key_comment" {
  description = "(Optional) An optional comment about the public key."
  default     = null
}

variable "cloudfront_public_key_name" {
  description = "(Optional) The name for the public key. By default generated by Terraform."
  default     = null
}

variable "cloudfront_public_key_name_prefix" {
  description = "(Optional) The name for the public key. Conflicts with cloudfront_public_key_name."
  default     = null
}

#---------------------------------------------------
# AWS cloudfront origin access identity
#---------------------------------------------------
variable "enable_cloudfront_origin_access_identity" {
  description = "Enable cloudfront origin access identity usage"
  default     = false
}

variable "cloudfront_origin_access_identity_comment" {
  description = "(Optional) - An optional comment for the origin access identity."
  default     = null
}

#---------------------------------------------------
# AWS cloudfront realtime log config
#---------------------------------------------------
variable "enable_cloudfront_realtime_log_config" {
  description = "Enable cloudfront realtime log config usage"
  default     = false
}

variable "cloudfront_realtime_log_config_name" {
  description = "The unique name to identify this real-time log configuration."
  default     = ""
}

variable "cloudfront_realtime_log_config_sampling_rate" {
  description = "(Required) The sampling rate for this real-time log configuration. The sampling rate determines the percentage of viewer requests that are represented in the real-time log data. An integer between 1 and 100, inclusive."
  default     = 1
}

variable "cloudfront_realtime_log_config_fields" {
  description = "(Required) The fields that are included in each real-time log record."
  default     = []
}

variable "cloudfront_realtime_log_config_endpoints" {
  description = "(Required) The Amazon Kinesis data streams where real-time log data is sent."
  default     = {}
}

#---------------------------------------------------
# AWS cloudfront origin request policy
#---------------------------------------------------
variable "enable_cloudfront_origin_request_policy" {
  description = "Enable cloudfront origin request policy usage"
  default     = false
}

variable "cloudfront_origin_request_policy_name" {
  description = "Unique name to identify the origin request policy."
  default     = ""
}

variable "cloudfront_origin_request_policy_comment" {
  description = "(Optional) Comment to describe the origin request policy."
  default     = null
}

variable "cloudfront_origin_request_policy_cookies_config" {
  description = "(Required) Object that determines whether any cookies in viewer requests (and if so, which cookies) are included in the origin request key and automatically included in requests that CloudFront sends to the origin. See Cookies Config for more information."
  default     = {}
}

variable "cloudfront_origin_request_policy_headers_config" {
  description = "(Required) Object that determines whether any HTTP headers (and if so, which headers) are included in the origin request key and automatically included in requests that CloudFront sends to the origin. See Headers Config for more information."
  default     = {}
}

variable "cloudfront_origin_request_policy_query_strings_config" {
  description = "(Required) Object that determines whether any URL query strings in viewer requests (and if so, which query strings) are included in the origin request key and automatically included in requests that CloudFront sends to the origin. See Query Strings Config for more information."
  default     = {}
}

#---------------------------------------------------
# AWS cloudfront cache policy
#---------------------------------------------------
variable "enable_cloudfront_cache_policy" {
  description = "Enable cloudfront cache policy usage"
  default     = false
}

variable "cloudfront_cache_policy_stack" {
  description = "Set properties for cloudfront cache policy"
  default     = []
}
