#---------------------------------------------------
# Consul prepared query
#---------------------------------------------------
output "consul_prepared_query_id" {
  description = "The ID of the prepared query, generated by Consul."
  value       = element(concat(consul_prepared_query.prepared_query.*.id, [""]), 0)
}
