#-----------------------------------------------------------
# Azure virtual desktop workspace
#-----------------------------------------------------------
output "virtual_desktop_workspace_id" {
  description = "The ID of the Virtual Desktop Workspace."
  value       = element(concat(azurerm_virtual_desktop_workspace.virtual_desktop_workspace.*.id, [""]), 0)
}

#-----------------------------------------------------------
# Azure virtual desktop workspace application group association
#-----------------------------------------------------------
output "virtual_desktop_workspace_application_group_association_id" {
  description = "The ID of the Virtual Desktop Workspace Application Group association."
  value       = element(concat(azurerm_virtual_desktop_workspace_application_group_association.virtual_desktop_workspace_application_group_association.*.id, [""]), 0)
}

#-----------------------------------------------------------
# Azure virtual desktop scaling plan
#-----------------------------------------------------------
output "virtual_desktop_scaling_plan_id" {
  description = "The ID of the Virtual Desktop Scaling Plan."
  value       = element(concat(azurerm_virtual_desktop_scaling_plan.virtual_desktop_scaling_plan.*.id, [""]), 0)
}

#-----------------------------------------------------------
# Azure virtual desktop host pool
#-----------------------------------------------------------
output "virtual_desktop_host_pool_id" {
  description = "The ID of the Virtual Desktop Host Pool."
  value       = element(concat(azurerm_virtual_desktop_host_pool.virtual_desktop_host_pool.*.id, [""]), 0)
}

#-----------------------------------------------------------
# Azure virtual desktop host pool registration info
#-----------------------------------------------------------
output "virtual_desktop_host_pool_registration_info_id" {
  description = "The ID of the Virtual Desktop Host Pool Registration Info resource."
  value       = element(concat(azurerm_virtual_desktop_host_pool_registration_info.virtual_desktop_host_pool_registration_info.*.id, [""]), 0)
}

output "virtual_desktop_host_pool_registration_info_token" {
  description = "The registration token generated by the Virtual Desktop Host Pool for registration of session hosts."
  value       = element(concat(azurerm_virtual_desktop_host_pool_registration_info.virtual_desktop_host_pool_registration_info.*.token, [""]), 0)
}

#-----------------------------------------------------------
# Azure virtual desktop application
#-----------------------------------------------------------
output "virtual_desktop_application_id" {
  description = "The ID of the Virtual Desktop Application."
  value       = element(concat(azurerm_virtual_desktop_application.virtual_desktop_application.*.id, [""]), 0)
}

#-----------------------------------------------------------
# Azure virtual desktop application group
#-----------------------------------------------------------
output "virtual_desktop_application_group_id" {
  description = "The ID of the Virtual Desktop Application Group."
  value       = element(concat(azurerm_virtual_desktop_application_group.virtual_desktop_application_group.*.id, [""]), 0)
}