#-----------------------------------------------------------
# Global or/and default variables
#-----------------------------------------------------------
variable "name" {
  description = "Name to be used on all resources as prefix"
  default     = "TEST"
}

variable "environment" {
  description = "Environment for service"
  default     = "STAGE"
}

variable "tags" {
  description = "A list of tag blocks."
  type        = map(string)
  default     = {}
}

#-----------------------------------------------------------
# AWS EFS
#-----------------------------------------------------------
variable "enable_efs_file_system" {
  description = "Enable EFS usage"
  default     = false
}

variable "efs_file_system_name" {
  description = "Set name for AWS EFS"
  default     = ""
}


variable "efs_file_system_performance_mode" {
  description = "The file system performance mode. Can be either 'generalPurpose' or 'maxIO' (Default: 'generalPurpose')."
  default     = "generalPurpose"
}

variable "efs_file_system_encrypted" {
  description = "If true, the disk will be encrypted."
  default     = true
}

variable "efs_file_system_kms_key_id" {
  description = "The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true."
  default     = ""
}

variable "efs_file_system_creation_token" {
  description = "(Optional) A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. See Elastic File System user guide for more information."
  default     = ""
}

variable "efs_file_system_provisioned_throughput_in_mibps" {
  description = "(Optional) The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned."
  default     = null
}

variable "efs_file_system_throughput_mode" {
  description = "(Optional) Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned. When using provisioned, also set provisioned_throughput_in_mibps."
  default     = null
}

variable "efs_file_system_lifecycle_policy" {
  description = "(Optional) A file system lifecycle policy object"
  default     = []
}

#-----------------------------------------------------------
# AWS EFS mount targets
#-----------------------------------------------------------
variable "enable_efs_mount_target" {
  description = "Enable EFS mount target usage"
  default     = false
}

variable "efs_mount_target_subnet_ids" {
  description = "The ID of the subnets to add the mount target in."
  default     = []
}

variable "efs_mount_target_file_system_id" {
  description = "(Required) The ID of the file system for which the mount target is intended."
  default     = ""
}

variable "efs_mount_target_ip_address" {
  description = "(Optional) The address (within the address range of the specified subnet) at which the file system may be mounted via the mount target."
  default     = null
}

variable "efs_mount_target_security_groups" {
  description = "description"
  default     = []
}

#---------------------------------------------------
# AWS EFS file system policy
#---------------------------------------------------
variable "enable_efs_file_system_policy" {
  description = "Enable EFS file system policy usage"
  default     = false
}

variable "efs_file_system_policy_file_system_id" {
  description = "The ID of the EFS file system."
  default     = ""
}

variable "efs_file_system_policy_policy" {
  description = "(Required) The JSON formatted file system policy for the EFS file system. see Docs for more info."
  default     = null
}

#---------------------------------------------------
# AWS EFS access point
#---------------------------------------------------
variable "enable_efs_access_point" {
  description = "Enable EFS access point usage"
  default     = false
}

variable "efs_access_point_file_system_id" {
  description = "The ID of the file system for which the access point is intended."
  default     = ""
}

variable "efs_access_point_name" {
  description = "Set name for EFS access point"
  default     = ""
}

variable "efs_access_point_posix_user" {
  description = "(Optional) The operating system user and group applied to all file system requests made using the access point."
  default     = []
}

variable "efs_access_point_root_directory" {
  description = "(Optional) Specifies the directory on the Amazon EFS file system that the access point provides access to. "
  default     = []
}
