#-----------------------------------------------------------
# Global or/and default variables
#-----------------------------------------------------------
variable "name" {
  description = "Name to be used on all resources as prefix"
  default     = "TEST-codedeploy"
}

variable "environment" {
   description = "Environment for service"
   default     = "STAGE"
}

variable "tags" {
  description = "A list of tag blocks."
  type        = map(string)
  default     = {}
}

#-----------------------------------------------------------
# AWS EFS
#-----------------------------------------------------------
variable "enable_efs_file_system" {
  description   = "Enable EFS usage"
  default       = false
}

variable "efs_file_system_name" {
  description   = "Set name for AWS EFS"
  default       = ""
}


variable "performance_mode" {
    description = "The file system performance mode. Can be either 'generalPurpose' or 'maxIO' (Default: 'generalPurpose')."
    default     = "generalPurpose"
}

variable "encrypted" {
    description = "If true, the disk will be encrypted."
    default     = true
}

variable "kms_key_id" {
    description = "The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true."
    default     = ""
}

variable "creation_token" {
    description = "(Optional) A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. See Elastic File System user guide for more information."
    default     = ""
}

variable "provisioned_throughput_in_mibps" {
  description   = "(Optional) The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned."
  default       = null
}

variable "throughput_mode" {
  description   = "(Optional) Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned. When using provisioned, also set provisioned_throughput_in_mibps."
  default       = null
}

variable "lifecycle_policy" {
  description   = "(Optional) A file system lifecycle policy object"
  default       = []
}

#-----------------------------------------------------------
# AWS EFS mount targets
#-----------------------------------------------------------
variable "enable_efs_mount_target" {
  description   = "Enable efs_mount_target"
  default       = false
}

variable "subnet_ids" {
    description = "The ID of the subnets to add the mount target in."
    default     = []
}

variable "file_system_id" {
  description   = "(Required) The ID of the file system for which the mount target is intended."
  default       = ""
}

variable "ip_address" {
  description   = "(Optional) The address (within the address range of the specified subnet) at which the file system may be mounted via the mount target."
  default       = null
}

variable "security_groups" {
  description   = "description"
  default       = []
}
