#-----------------------------------------------------------
# Global or/and default variables
#-----------------------------------------------------------
variable "name" {
  description = "Name to be used on all resources as prefix"
  default     = "TEST"
}

variable "environment" {
  description = "Environment for service"
  default     = "STAGE"
}

variable "tags" {
  description = "A list of tag blocks."
  type        = map(string)
  default     = {}
}

#-----------------------------------------------------------
# ELB
#-----------------------------------------------------------
variable "enable_elb" {
  description = "Enable ELB usage"
  default     = false
}

variable "elb_name" {
  description = "The name of the ELB. By default generated by Terraform."
  default     = ""
}

variable "elb_availability_zones" {
  description = "Availability zones for AWS ASG"
  default     = null
}

variable "elb_security_groups" {
  description = "A list of security group IDs to assign to the ELB. Only valid if creating an ELB within a VPC"
  default     = []
}

variable "elb_subnets" {
  description = "A list of subnet IDs to attach to the ELB"
  default     = null
}

variable "elb_internal" {
  description = "If true, ELB will be an internal ELB"
  default     = false
}

variable "elb_cross_zone_load_balancing" {
  description = "Enable cross-zone load balancing. Default: true"
  default     = true
}

variable "elb_idle_timeout" {
  description = "The time in seconds that the connection is allowed to be idle. Default: 60"
  default     = 60
}

variable "elb_connection_draining" {
  description = "Boolean to enable connection draining. Default: false"
  default     = false
}

variable "elb_connection_draining_timeout" {
  description = "The time in seconds to allow for connections to drain. Default: 300"
  default     = 300
}

variable "elb_access_logs" {
  description = "An access logs block. Uploads access logs to S3 bucket"
  default     = []
}

variable "elb_listener" {
  description = "A list of Listener block"
  default     = []
}

variable "elb_health_check" {
  description = " Health check"
  default     = []
}

#-----------------------------------------------------------
# ELB attachment
#-----------------------------------------------------------
variable "enable_elb_attachment" {
  description = "Enable elb_attachment usage"
  default     = false
}

variable "elb_attachment_instances" {
  description = " Instances ID to add them to ELB"
  default     = []
}

variable "elb_attachment_elb_id" {
  description = "ID of ELB"
  default     = ""
}

#-----------------------------------------------------------
# AWS ELB app cookie stickiness policy
#-----------------------------------------------------------
variable "enable_app_cookie_stickiness_policy" {
  description = "Enable app cookie stickiness policy usage"
  default     = false
}

variable "app_cookie_stickiness_policy_stack" {
  description = "Set stack settings for app cookie stickness policy"
  default     = []
}

#---------------------------------------------------
# AWS ELB lb cookie stickiness policy
#---------------------------------------------------
variable "enable_lb_cookie_stickiness_policy" {
  description = "Enable lb cookie stickiness policy usage"
  default     = false
}

variable "lb_cookie_stickiness_policy_stack" {
  description = "Set stack settings for lb cookie stickness policy"
  default     = []
}

#---------------------------------------------------
# AWS ELB proxy protocol policy
#---------------------------------------------------
variable "enable_proxy_protocol_policy" {
  description = "Enable proxy protocol policy usage"
  default     = false
}

variable "proxy_protocol_policy_load_balancer" {
  description = "The name of the ELB."
  default     = ""
}

variable "proxy_protocol_policy_instance_ports" {
  description = "(Required) Instance ID to place in the ELB pool."
  default     = null
}

#---------------------------------------------------
# AWS ELB lb ssl negotiation policy
#---------------------------------------------------
variable "enable_lb_ssl_negotiation_policy" {
  description = "Enable lb ssl negotiation policy"
  default     = false
}

variable "lb_ssl_negotiation_policy_name" {
  description = "The name of the SSL negotiation policy."
  default     = ""
}

variable "lb_ssl_negotiation_policy_load_balancer" {
  description = "The load balancer to which the policy should be attached."
  default     = ""
}

variable "lb_ssl_negotiation_policy_lb_port" {
  description = "(Required) The load balancer port to which the policy should be applied. This must be an active listener on the load balancer."
  default     = null
}

variable "lb_ssl_negotiation_policy_attribute" {
  description = "(Optional) An SSL Negotiation policy attribute"
  default     = []
}

#---------------------------------------------------
# AWS load balancer policy
#---------------------------------------------------
variable "enable_load_balancer_policy" {
  description = "Enable load balancer policy usage"
  default     = false
}

variable "load_balancer_policy_load_balancer_name" {
  description = "(Required) The load balancer on which the policy is defined."
  default     = ""
}

variable "load_balancer_policy_policy_name" {
  description = "The name of the load balancer policy."
  default     = ""
}

variable "load_balancer_policy_policy_type_name" {
  description = "(Required) The policy type."
  default     = null
}

variable "load_balancer_policy_policy_attribute" {
  description = "(Optional) Policy attribute to apply to the policy."
  default     = []
}

#---------------------------------------------------
# AWS load balancer backend server policy
#---------------------------------------------------
variable "enable_load_balancer_backend_server_policy" {
  description = "Enable load balancer backend server policy usage"
  default     = false
}

variable "load_balancer_backend_server_policy_load_balancer_name" {
  description = "The load balancer to attach the policy to."
  default     = ""
}

variable "load_balancer_backend_server_policy_instance_port" {
  description = "(Required) The instance port to apply the policy to."
  default     = null
}

variable "load_balancer_backend_server_policy_policy_names" {
  description = "(Required) List of Policy Names to apply to the backend server."
  default     = []
}

#---------------------------------------------------
# AWS load balancer listener policy
#---------------------------------------------------
variable "enable_load_balancer_listener_policy" {
  description = "Enable load balancer listener policy"
  default     = false
}

variable "load_balancer_listener_policy_load_balancer_name" {
  description = "The load balancer to attach the policy to."
  default     = ""
}

variable "load_balancer_listener_policy_load_balancer_port" {
  description = "(Required) The load balancer listener port to apply the policy to."
  default     = null
}

variable "load_balancer_listener_policy_policy_names" {
  description = "(Required) List of Policy Names to apply to the backend server."
  default     = []
}
