#-----------------------------------------------------------
# Global or/and default variables
#-----------------------------------------------------------
variable "name" {
  description = "Name to be used on all resources as prefix"
  default     = "TEST"
}

variable "environment" {
    description = "Environment for service"
    default     = "STAGE"
}

#-----------------------------------------------------------
# IAM openid connect provider
#-----------------------------------------------------------
variable "enable_iam_openid_connect_provider" {
  description   = "Enable IAM openID connect provider usage"
  default       = false
}

variable "iam_openid_connect_provider_url" {
  description   = "(Required) The URL of the identity provider. Corresponds to the iss claim. Ex: https://accounts.google.com"
  default       = ""
}

variable "iam_openid_connect_provider_client_id_list" {
  description   = "(Required) A list of client IDs (also known as audiences). When a mobile or web app registers with an OpenID Connect provider, they establish a value that identifies the application. (This is the value that's sent as the client_id parameter on OAuth requests.)"
  default       = []
}

variable "iam_openid_connect_provider_thumbprint_list" {
  description   = "(Required) A list of server certificate thumbprints for the OpenID Connect (OIDC) identity provider's server certificate(s)."
  default       = []
}

#-----------------------------------------------------------
# IAM saml provider
#-----------------------------------------------------------
variable "enable_iam_saml_provider" {
  description   = "Enable IAM SAML provider usage"
  default       = false
}

variable "iam_saml_provider_name" {
  description   = "The name of the provider to create."
  default       = ""
}

variable "iam_saml_provider_saml_metadata_document" {
  description   = "(Required) An XML document generated by an identity provider that supports SAML 2.0."
  default       = ""
}
