#-----------------------------------------------------------
# Global or/and default variables
#-----------------------------------------------------------
variable "name" {
  description = "Name to be used on all resources as prefix"
  default     = "TEST"
}

variable "environment" {
  description = "Environment for service"
  default     = "STAGE"
}

variable "tags" {
  description = "A list of tag blocks. Each element should have keys named key, value, etc."
  type        = map(string)
  default     = {}
}

#---------------------------------------------------
# AWS Transfer server
#---------------------------------------------------
variable "enable_transfer_server" {
  description = "Enable transfer server usage"
  default     = false
}

variable "transfer_server_endpoint_type" {
  description = "(Optional) The type of endpoint that you want your SFTP server connect to. If you connect to a VPC_ENDPOINT, your SFTP server isn't accessible over the public internet. If you want to connect your SFTP server via public internet, set PUBLIC. Defaults to PUBLIC."
  default     = "PUBLIC"
}

variable "transfer_server_invocation_role" {
  description = "(Optional) Amazon Resource Name (ARN) of the IAM role used to authenticate the user account with an identity_provider_type of API_GATEWAY."
  default     = null
}

variable "transfer_server_host_key" {
  description = "(Optional) RSA private key (e.g. as generated by the ssh-keygen -N '' -f my-new-server-key command)."
  default     = null
}

variable "transfer_server_url" {
  description = "(Optional) - URL of the service endpoint used to authenticate users with an identity_provider_type of API_GATEWAY."
  default     = null
}

variable "transfer_server_identity_provider_type" {
  description = "(Optional) The mode of authentication enabled for this service. The default value is SERVICE_MANAGED, which allows you to store and access SFTP user credentials within the service. API_GATEWAY indicates that user authentication requires a call to an API Gateway endpoint URL provided by you to integrate an identity provider of your choice."
  default     = null
}

variable "transfer_server_logging_role" {
  description = "(Optional) Amazon Resource Name (ARN) of an IAM role that allows the service to write your SFTP users’ activity to your Amazon CloudWatch logs for monitoring and auditing purposes."
  default     = null
}

variable "transfer_server_force_destroy" {
  description = "(Optional) A boolean that indicates all users associated with the server should be deleted so that the Server can be destroyed without error. The default value is false."
  default     = false
}

variable "transfer_server_endpoint_details" {
  description = "(Optional) The virtual private cloud (VPC) endpoint settings that you want to configure for your SFTP server."
  default     = []
}

variable "transfer_server_name" {
  description = "Set transfer server name"
  default     = ""
}

#---------------------------------------------------
# AWS Transfer user
#---------------------------------------------------
variable "enable_transfer_user" {
  description = "Enable transfer user usage"
  default     = false
}

variable "transfer_user_server_id" {
  description = "The Server ID of the Transfer Server (e.g. s-12345678)"
  default     = ""
}

variable "transfer_user_name" {
  description = "The name used for log in to your SFTP server."
  default     = ""
}

variable "transfer_user_role" {
  description = "(Requirement) Amazon Resource Name (ARN) of an IAM role that allows the service to controls your user’s access to your Amazon S3 bucket."
  default     = null
}

variable "transfer_user_home_directory" {
  description = "(Optional) The landing directory (folder) for a user when they log in to the server using their SFTP client. It should begin with a /. The first item in the path is the name of the home bucket (accessible as 'Transfer:HomeBucket' in the policy) and the rest is the home directory (accessible as 'Transfer:HomeDirectory' in the policy). For example, /example-bucket-1234/username would set the home bucket to example-bucket-1234 and the home directory to username."
  default     = null
}

variable "transfer_user_policy" {
  description = "(Optional) An IAM JSON policy document that scopes down user access to portions of their Amazon S3 bucket. IAM variables you can use inside this policy include 'Transfer:UserName', 'Transfer:HomeDirectory', and 'Transfer:HomeBucket'. Since the IAM variable syntax matches Terraform's interpolation syntax, they must be escaped inside Terraform configuration strings ('Transfer:UserName'). These are evaluated on-the-fly when navigating the bucket."
  default     = null
}

#---------------------------------------------------
# AWS Transfer ssh key
#---------------------------------------------------
variable "enable_transfer_ssh_key" {
  description = "Enable transfer ssh key usage"
  default     = false
}

variable "transfer_ssh_key_server_id" {
  description = "The Server ID of the Transfer Server (e.g. s-12345678)"
  default     = ""
}

variable "transfer_ssh_key_user_name" {
  description = "The name of the user account that is assigned to one or more servers."
  default     = ""
}

variable "transfer_ssh_key_body" {
  description = "(Requirement) The public key portion of an SSH key pair."
  default     = null
}
