variable "project" {
  description = "(Optional) The project ID that the service belongs to. If not provided, provider project is used."
  default     = ""    
} 

variable "enable_endpoints_service_openapi" {
    description = "Enable endpoints service openapi usage"
    default     = "false"
}

variable "openapi_config" {
    description = "(Optional) The full text of the OpenAPI YAML configuration as described. Set path to openapi config file. Ex: openapi_spec.yml."
    default     = ""
}

variable "enable_endpoints_service_grpc" {
    description = "Enable endpoints service grpc usage"
    default     = "false"
}

variable "grpc_config" {
    description = "(Optional) The full text of the Service Config YAML file (Example located here). If provided, must also provide protoc_output. open_api config must not be provided. Set path to grpc config file. Ex: service_spec.yml"
    default     = ""
}

variable "protoc_output_base64" {
    description = "(Optional) The full contents of the Service Descriptor File generated by protoc. This should be a compiled .pb file, base64-encoded. Set path to protoc output file. Ex: compiled_descriptor_file.pb"
    default     = ""
}

variable "service_name" {
    description = "(Required) The name of the service. Usually of the form $apiname.endpoints.$projectid.cloud.goog."
    default     = ""
}
