{
   "rules":[
      {
         "rule-type":"selection",
         "rule-id":"1",
         "rule-name":"1",
         "object-locator":{
            "schema-name":"%",
            "table-name":"%"
         },
         "rule-action":"include"
      }
   ]
}